### ISSUE TITLE
When i try to build with docker this happen

### ISSUE THREAD

**Issue by Tsumiicode** [checkra1n/pongoOS#69]
root@toby-GA-970A-DS3:/home/toby# docker run docker.pkg.github.com/checkra1n/pongoos/build-pongo:latest
make: *** No targets specified and no makefile found.  Stop.

**Comment by Tsumiicode** [comment]
right so i got it working but now i get this error when using boot linux py
toby@toby-GA-970A-DS3:~/pongoOS/scripts$ sudo python3 load_linux.py -k Linux.lzma -d dtbpack
Loading device tree...
Device tree loaded successfully.
Loading kernel...
Traceback (most recent call last):
  File "load_linux.py", line 71, in <module>
    dev.write(2, kernel, 1000000)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 979, in write
    return fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 837, in bulk_write
    return self.__write(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
